<?xml version="1.0" encoding="UTF-8"?>
<!-- bookstore-inlineDTD.xml -->
<!DOCTYPE bookstore [
  <!ELEMENT bookstore (book+)>
  <!ELEMENT book (title, author+, category*, language?, year?, edition?, price)>
    <!ATTLIST book ISBN CDATA #REQUIRED>
  <!ELEMENT title    (#PCDATA)>
  <!ELEMENT author   (#PCDATA)>
  <!ELEMENT category (#PCDATA)>
  <!ELEMENT language (#PCDATA)>
  <!ELEMENT year     (#PCDATA)>
  <!ELEMENT edition  (#PCDATA)>
  <!ELEMENT price    (#PCDATA)>
]>
<bookstore>
  <book ISBN="0123456001">
    <title>Java For Dummies</title>
    <author>Max Meier</author>
    <category>Programming</category>
    <year>2012</year>
    <edition>7</edition>
    <price>19.99</price>
  </book>
  <book ISBN="0123456002">
    <title>More Java For Peoples</title>
    <author>Smart Gzu</author>
    <category>Programming</category>
    <year>2001</year>
    <price>25.99</price>
  </book>
  <book ISBN="0123456010">
    <title>The Complete Guide to Boxing</title>
    <author>Bill Bone</author>
    <author>Kurt Face</author>
    <author>Eva Sand</author>
    <category>Boxing</category>
    <category>Sport</category>
    <language>English</language>
    <year>2010</year>
    <edition>2</edition>
    <price>49.99</price>
  </book>
</bookstore>